### PR TITLE
Add CNCF section and LF Footer

### LINKED ISSUE #25: Add LF footer and follow CNCF website guidelines
As part of CNCF onboarding we'll want to support this: https://github.com/cncf/foundation/blob/master/website-guidelines.md

### PR DESCRIPTION
**Pull request by srpomeroy**
Added required Linux Foundation footer along with CNCF Sandbox Project section on landing page.

Fixes #25

### CODE REVIEW

**Comment by srpomeroy** [comment]
It's been ~20 years since I've written any HTML and 0 days since I've used Tailwinds CSS, react, or docusaurus. Would appreciate a review and any feedback you may have @dwbrown2 @avrodrigues5 @Adam-Stack-PM

**Comment by dwbrown2** [comment]
Still got it @srpomeroy!!! Looking good to me. Here are two minor suggestion, but feel free to take or leave. 

1. I think we could even move the CNCF sandbox section above founding contributors. @alexkubecost may disagree
2. I might left align trademark language in footer?

image

Here's one other example:

image

**Comment by alexkubecost** [comment]
I'm in agreement! It was not clear to me in the onboarding instructions when we can begin to surface the CNCF logo, but any opportunity to showcase our governing organization the better, IMO!

**Comment by Adam-Stack-PM** [comment]
Found this. My interpretation is we can include the logo towards the bottom of the page. 

CNCF requests that graduated and incubating projects include the sentence “We are a Cloud Native Computing Foundation project.” and the CNCF logo near the bottom of their project homepage. Sandbox-level projects should include the sentence “We are a Cloud Native Computing Foundation sandbox project.” and the CNCF logo. We also appreciate a link to KubeCon + CloudNativeCon as the events approach.

Copied from point 6 here https://github.com/cncf/foundation/blob/main/website-guidelines.md

**Comment by Adam-Stack-PM** [comment]
Based on my interpretation of the CNCF guidelines, have two additional changes to consider. 

1. Reword "Opencost created by Kubecost" To “Opencost was originally created by Kubecost"
2. It is not clear if we can link to Kubescost on the homepage. See issue #31

**Comment by dwbrown2** [comment]
> Based on my interpretation of the CNCF guidelines, have two additional changes to consider.
> 
> 1. Reword "Opencost created by Kubecost" To “Opencost was originally created by Kubecost"
> 2. It is not clear if we can link to Kubescost on the homepage. See issue [Add an enterprise support page to Opencost.io #31](https://github.com/kubecost/opencost-website/issues/31)

Good callout, I think both live outside of scope of this PR but let me know if others feel differently.

**Review by dwbrown2 — APPROVED** [review]

**Comment by Adam-Stack-PM** [comment]
@dwbrown2 Medium opinion here.  #1 may be in scope.  Mainly to ensure we put our best foot forward. In their guidelines, they provide this wording as an example.

**Comment by Adam-Stack-PM** [comment]
100% agree with point two. I brought that up as it could be a good opportunity for Kubecost down the road if we  want to leverage it. 

For point #1 referring to the headline in the footer.   Wondering if we want to speak more to the intent of open source projects? Kubecost created it and now we are turning it over to the community.  For example "Opencost was originally created by Kubecost"

Screen Shot 2022-06-30 at 2 21 09 PM

**Comment by srpomeroy** [comment]
@Adam-Stack-PM Apologies, I was referring to guideline 2 on the CNCF guideline doc which is the reference to the creators you are referring to. Happy to make the change, but I think we are ok with the current verbiage.

**Comment by Adam-Stack-PM** [comment]
Sounds good to me.  Thanks for crushing this task.

**Pull request merged**
